// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt53JkRkxQggelE_exBWFiPhYpwCTj9Ew',
    appId: '1:321627385762:web:dd8e43202f0a1a81cdccfb',
    messagingSenderId: '321627385762',
    projectId: 'infs-tracking',
    authDomain: 'infs-tracking.firebaseapp.com',
    databaseURL: 'https://infs-tracking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'infs-tracking.appspot.com',
    measurementId: 'G-PY9YDJX5E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL_mE47IsxE5GNR1q7XIPZym-rvBqy3Pk',
    appId: '1:321627385762:android:49b0fc87a229ce9ccdccfb',
    messagingSenderId: '321627385762',
    projectId: 'infs-tracking',
    databaseURL: 'https://infs-tracking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'infs-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYYKDhUPnlTSG3sPtCW6cH74zbugkPGMM',
    appId: '1:321627385762:ios:02da1bbf4160657acdccfb',
    messagingSenderId: '321627385762',
    projectId: 'infs-tracking',
    databaseURL: 'https://infs-tracking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'infs-tracking.appspot.com',
    androidClientId: '321627385762-4f3u0nn2u6jh0sv4qe36mh1ul7t1lvho.apps.googleusercontent.com',
    iosClientId: '321627385762-gsfkbih89nqkfr84i6decv8jlrn758r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.insuTrackingAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYYKDhUPnlTSG3sPtCW6cH74zbugkPGMM',
    appId: '1:321627385762:ios:4510a6c779f70704cdccfb',
    messagingSenderId: '321627385762',
    projectId: 'infs-tracking',
    databaseURL: 'https://infs-tracking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'infs-tracking.appspot.com',
    androidClientId: '321627385762-4f3u0nn2u6jh0sv4qe36mh1ul7t1lvho.apps.googleusercontent.com',
    iosClientId: '321627385762-lbc7a2s304dt8t8250vnlpv2q23filip.apps.googleusercontent.com',
    iosBundleId: 'com.example.insuTrackingAdmin.RunnerTests',
  );
}
